[workspace]
members = [
    "eth_test_parser",
    "evm_test_runner",
    "common",
]

[workspace.package]
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["Polygon Zero <bgluth@polygon.technology>"]
repository = "https://github.com/0xPolygonZero/evm-tests"
keywords = ["cryptography", "SNARK", "PLONK", "FRI", "plonky2"]
categories = ["cryptography"]

[workspace.dependencies]
anyhow = { version = "1.0.71", features = ["backtrace"] }
clap = {version = "4.2.7", features = ["derive"] }
ethereum-types = "0.14.1"
mpt_trie = { git = "https://github.com/0xPolygonZero/zk_evm.git", rev = "62b6f5a8fd11cfc74d32f8d598d395a46f148502" }
flexi_logger = { version = "0.25.4", features = ["async"] }
futures = "0.3.28"
keccak-hash = "0.10.0"
log = "0.4.17"
plonky2 = { git = "https://github.com/0xPolygonZero/plonky2.git", rev = "710225c9e0ac5822b2965ce74951cf000bbb8a2c" }
evm_arithmetization = { git = "https://github.com/0xPolygonZero/zk_evm.git", rev = "62b6f5a8fd11cfc74d32f8d598d395a46f148502" }
serde = "1.0.163"
serde_cbor = "0.11.2"
tokio = { version = "1.28.1" }

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
