[package]
name = "common"
description = "Common logic shared between the parser and the runner."
version = "0.1.0"
authors = ["Polygon Zero <bgluth@polygon.technology>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "1.0.71", features = ["backtrace"] }
ethereum-types = "0.14.1"
eth_trie_utils = "0.6.0"
flexi_logger = { version = "0.25.4", features = ["async"] }
plonky2_evm = { git = "https://github.com/mir-protocol/plonky2.git", rev = "6f98fd762885e9b5343af5f0e3f0c9c90e8cf3ab" }
serde = {version = "1.0.163", features = ["derive"] }
revm = { version = "3.3.0", features = ["serde"] }
ruint = { version = "1.8.0", features = ["primitive-types"] }
