[package]
name = "common"
description = "Common logic shared between the parser and the runner."
version = "0.1.0"
authors = ["Polygon Zero <bgluth@polygon.technology>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "1.0.66", features = ["backtrace"] }
ethereum-types = "0.14.0"
eth_trie_utils = "0.5.0"
flexi_logger = { version = "0.25.1", features = ["async"] }
plonky2_evm = { git = "https://github.com/mir-protocol/plonky2.git", rev = "b667c07497d5343e5d239a5980debf6401ac775f" }
serde = {version = "1.0.147", features = ["derive"] }
revm = { version = "3.0.0", features = ["serde"] }
ruint = { version = "1.7.0", features = ["primitive-types"] }
