[package]
name = "eth_test_parser"
description = "Downloads and parses common Ethereum tests into a format runnable by Polygon Zero's EVM."
version = "0.1.0"
authors = ["Polygon Zero <bgluth@polygon.technology>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { path = "../common" }
plonky2_evm = { git = "https://github.com/mir-protocol/plonky2.git", rev = "c874fc54888b99de360ecd6661d7e3c7f961075c" }
eth-trie-utils = { git = "https://github.com/mir-protocol/eth-trie-utils.git", rev = "3deff443dc62e936d2522f98fc1db41c67ccb86e" }

clap = {version = "3.2.17", features = ["derive"] }
anyhow = { version = "1.0", features = ["backtrace"] }
tokio = { version = "1.20.1", features = ["rt", "rt-multi-thread", "macros"] }
chrono = "0.4.22"
log = "0.4.17"
backtrace = "0.3.66"
serde_json = "1.0.85"
ethereum-types = "0.13.1"
hex = "0.4.3"
bitvec = "1.0.1"
itertools = "0.10.3"
num-traits = "0.2.15"
sha3 = "0.10.4"
