[package]
name = "eth_test_parser"
description = "Downloads and parses common Ethereum tests into a format runnable by Polygon Zero's EVM."
version = "0.1.0"
authors = ["Polygon Zero <bgluth@polygon.technology>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { path = "../common" }
eth_trie_utils = "0.2.1"
plonky2_evm = { git = "https://github.com/mir-protocol/plonky2.git", rev = "06475c2b61a0d3b26d3f3ded791456052b94251b" }

anyhow = { version = "1.0.65", features = ["backtrace"] }
clap = {version = "4.0.14", features = ["derive"] }
ethereum-types = "0.14.0"
hex = "0.4.3"
keccak-hash = "0.10.0"
log = "0.4.17"
rlp = "0.5.1"
rlp-derive = "0.1.0"
serde = "1.0.145"
serde_bytes = "0.11.7"
serde_json = "1.0.86"
serde_with = "2.0.1"
serde_cbor = "0.11.2"
