[package]
name = "eth_test_parser"
description = "Downloads and parses common Ethereum tests into a format runnable by Polygon Zero's EVM."
version = "0.1.0"
authors = ["Polygon Zero <bgluth@polygon.technology>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { path = "../common" }
eth_trie_utils = "0.4.1"
plonky2_evm = { git = "https://github.com/mir-protocol/plonky2.git", rev = "f4e65feb65b74620f8c664ae82f8e68ee6f0370e" }

anyhow = { version = "1.0.66", features = ["backtrace"] }
clap = {version = "4.1.8", features = ["derive"] }
ethereum-types = "0.14.0"
hex = { version = "0.4.3", features = ["serde"] }
flexi_logger = { version = "0.25.1", features = ["async"] }
keccak-hash = "0.10.0"
log = "0.4.17"
rlp = "0.5.2"
rlp-derive = "0.1.0"
serde = "1.0.147"
serde_bytes = "0.11.7"
serde_json = "1.0.87"
serde_with = "2.0.1"
serde_cbor = "0.11.2"
tokio = { version = "1.21.2", features = ["full"] }
futures = "0.3.25"
revm = { version = "3.0.0", features = ["serde"] }
ruint = { version = "1.7.0", features = ["primitive-types"] }