[package]
name = "evm_test_runner"
description = "Test runner for Polygon Zero's EVM."
version = "0.1.0"
authors = ["Polygon Zero <bgluth@polygon.technology>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { path = "../common" }
plonky2_evm = { git = "https://github.com/mir-protocol/plonky2.git", rev = "928e8bc0e90507b5aeee2900a266bfc02dadb05b" }
plonky2 = { git = "https://github.com/mir-protocol/plonky2.git", rev = "928e8bc0e90507b5aeee2900a266bfc02dadb05b", features = ["timing"] }

anyhow = { version = "1.0", features = ["backtrace"] }
clap = {version = "3.2.17", features = ["derive"] }

ethereum-types = "0.13.1"
log = "0.4.17"
serde_json = "1.0.85"
tokio = {version = "1.21.1", features = ["fs", "macros", "rt-multi-thread"] }
tokio-stream = {version  = "0.1.10", features = ["fs"] }
askama = "0.11.1"
